### ISSUE TITLE
Fix json encoding to follow the spec

### ISSUE THREAD

**Issue by kcajmagic** [xmidt-org/wrp-go#18]
The current json encoding is incorrect and should follow the spec. https://github.com/Comcast/wrp-c/wiki/Web-Routing-Protocol#simple-request-response-definition

For example **_Destination_** is currently encoded as `Destination` and it should be `dest`, also empty fields should show as empty instead of null or empty value.

**Comment by kristinapathak** [comment]
fixed in https://github.com/Comcast/wrp-go/pull/19
