### ISSUE TITLE
ParseLocator: sanitize locator components 

### ISSUE THREAD

**Issue by denopink** [xmidt-org/wrp-go#210]
Currently, parsing the following string `"event:     /xmidt-test/2/config"` yields an authority with the value `     `.

We probably don't want this and should sanitize each locator component removing trailing and leading whitespaces.

Example:
![image](https://github.com/user-attachments/assets/a8fb3860-29c1-42b5-957c-ba282c71e91a)

**Comment by schmidtw** [comment]
Please add a test case for this & fix it.  That's a good find!
