### ISSUE TITLE
Add a way to get the original bytes of the wrp

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/wrp-go#37]
Consumers don't want to spend resources re-encoding a wrp into the same form they received it in (ex: MsgPack -> wrp struct -> MsgPack).  We want them to be able to easily use the original encoding if no fields have changed.  Otherwise, they have to re-encode.

**Comment by kristinapathak** [comment]
Related to https://github.com/xmidt-org/caduceus/issues/174

**Comment by kristinapathak** [comment]
@johnabass pointed out that this might be similar or what we want:
https://github.com/xmidt-org/wrp-go/blob/master/wrphttp/requestResponse.go#L30

**Comment by joe94** [comment]
Fixed by #43
